### PR TITLE
Allow using to string methods outside framework

### PR DESCRIPTION
**Pull request by bitomule**
Changed methods to public.

It didn't take me too much time finding another issue :)

### CODE REVIEW

**Comment by malcommac** [comment]
Shame on me, I think you will find several other similar issue around. This is my first attempt to make a Swift lib

**Comment by bitomule** [comment]
Nice, push cocoapods version when you can :)

**Comment by malcommac** [comment]
1.0.8 just published

**Comment by bitomule** [comment]
Great!

**Pull request merged**
