### PR TITLE
added isSameMonthOf and isSameYearOf

### PR DESCRIPTION
**Pull request by mccannmax**
added isSameMonthOf and isSameYearOf, cheers

### CODE REVIEW

**Comment by malcommac** [comment]
Just merged. Thank you :)
I'm thinking to merge all these comparing methods in a single call.
Could be something:
```swift
let isSameYear = date.compare("year",anotherDate)
```
What do you think?

**Comment by mccannmax** [comment]
Not unreasonable. I would do like so:
`let isSameYear = date.isSame(TIME_ENUM.Year, anotherDate)`
then the shorthand would read `let isSameYear = date.isSame(.Year, anotherDate)`
likewise: `date.isAfter(.Year, anotherDate)` & `date.isBefore(.Year, anotherDate)`

Cheers

**Comment by malcommac** [comment]
Well, right, enum is a more robust solution of course.
Anyway I think you can obtain the same result using `date.year == anotherDate.year` so I'm really torn about it. Could be more useful when grouping multiple components to compare in a single call.

**Comment by mccannmax** [comment]
True.  Would be useful when checking a date is after the current date down to hour/min/sec granularity. 
Example: 2015-05-05 9 AM > 2015-05-04 10AM, but date05.hour > date04.hour would return false
but `date05.isAfter(.Hour, date04)` would return true while ignore minutes and seconds.

**Pull request merged**
