### PR TITLE
DateTimeInterval#duration returns a wrong value

### PR DESCRIPTION
**Pull request by hackugyo**
`DateTimeInterval#duration` returns a negative value when it is initialized with values.
This means `DateTimeInterval#end` is not equal to the init value.
(iOS10 `DateInterval` can return correct values.)

### CODE REVIEW

**Comment by malcommac** [comment]
Thank you, it will be part of 4.1.8 release

**Comment by malcommac** [comment]
I think we have a problem here, I think I've made a mistake; can you explain me why we can't have `DateTimeInterval` with negative values?

**Comment by hackugyo** [comment]
I've checked #480 and now think we can allow `DateTimeInterval` with negative values!
The most reason I made PR #468 is from the inconsistency of `DateTimeInterval#end`. Your 00f9403c199ddede99a29f889931ddff76e543b1 solves this inconsistency.
@malcommac

**Comment by leviathan** [comment]
```
let startDate = "10:00"
let endDate = "12:00"

let dateDiff = startDate - endDate

>> raises Exception now in DateTimeInterval #67
>> precondition(end >= start, "Reverse intervals are not allowed")
```

why should it not be allowed to have a negative time interval ?!

**Comment by malcommac** [comment]
@leviathan I've fixed that, there is not any valid reason to keep this condition. Now `DateTimeInterval` supports negative interval. See the commit above.

**Pull request merged**
