### PR TITLE
Traditional Chinese support

### PR DESCRIPTION
**Pull request by rynecheow**

### CODE REVIEW

**Comment by malcommac** [comment]
Thank you @rynecheow . Added for 4.0.7

**Comment by malcommac** [comment]
I've a problem with readme merging into 4.0.7 branch.
Can you repost this PR directly in feature/4.0.7 branch? thx

**Comment by rynecheow** [comment]
Sure.

**Comment by malcommac** [comment]
Okay I'll close this; you can open a new PR on feature/4.0.7 and I'll merge it.
Thank you again.

**Comment by rynecheow** [comment]
Alright.

**Pull request closed without merging**
