### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Hout**
Hi,

AS mentioned, this pull request contains the StartOf and EndOf routines. I did the same whith the isSame functions.
I also adjusted the 1.days etc time intervaland the operators  to determine time differences more reliably for longer periods of time.
The date class function works nicer now IMHO, using the reference date (1-Jan-2001) as default value, however this might not be to your liking. It does not utilise the et fucntion which is something to complete. I also added a convenience version for week oriented dates.
I added nanoseconds to all routes for increased preciseness.
For comparison functions I used standard NSCalendar functions as opposed to yours.
 I also added a fair amount of test code.

### CODE REVIEW

**Comment by Hout** [comment]
Give me some time this weekend and I will merge your latest changes in and smooth out the duplicate code in set and date funcs

**Comment by Hout** [comment]
I added some more test code and the startOf does not work properly with different time zones when it is at midnight: it selects the previous day. Fixing...

**Comment by malcommac** [comment]
I'll look it this weekend (I was pretty busy this week).
Is there a conflict in this merge?

**Comment by Hout** [comment]
Yeps, don't worry I will take some time and rebase, merge etc, split up functionality and issue matching pull requests.
Fun project.

**Pull request closed without merging**
