### PR TITLE
Add Framework Support for OSX, tvOS, watchOS

### LINKED ISSUE #115: Mac OS X, watchOS, tvOS Support
I tried installing SwiftDate with Carthage, but only the framework for iOS was built. 

This was pretty easy to fix by adding an OS X target, and a shared scheme for it as well. However, I also had to comment out everything in `SwiftDate.h` because it was importing UIKit. Is this necessary? It seems like other Swift-only libraries don't have one.

I could pretty easily add some targets and schemes to get it to build for other OSs as well, but what are your thoughts on `SwiftDate.h`?

### PR DESCRIPTION
**Pull request by cjwirth**
This pull request fixes #115 

I am completely copying https://github.com/kishikawakatsumi/KeychainAccess in how I did this, but I think it's a cleaner approach than having multiple targets and schemes. 

I've gotten it to work locally with carthage. All the tests that were passing when I cloned `develop` still pass (there are a few that weren't passing due to some method change).

Sorry the diff is so big -> I changed the Pods so Quick/Nimble are only in the test target.

Go ahead, or let me know if you want some settings changed.

### CODE REVIEW

**Comment by Hout** [comment]
Daniele, should we merge this in for 3.0.0 or 3.1.0?

**Comment by malcommac** [comment]
I would investigate further before merge it, especially because we have not found an answer for this. I'll look at this the next week and we'll release a minor update to the new 3 branch

**Comment by malcommac** [comment]
Just solved in 3.0.1. Thank you for your report.
If you have problems make sure to remove Carthage folder in your project in order to do a clean fetch/clone/build.

**Comment by cjwirth** [comment]
Excellent, thanks! :rocket: 

Yeah, how you guys ended up fixing it up is probably better than my solution.
However, you might want to get rid of the extraneous `SwiftDate.xcodeproj` and `SwiftDate.xcworspace`, etc. files that aren't being used anymore.

**Comment by malcommac** [comment]
Just looked deeper on Keychain project :) Did you still see xcworkspace files? I've removed it along with cocoapods references.

**Comment by cjwirth** [comment]
:no_mouth: 
Nope! With a fresh clone, they are all gone! 
Sorry about that, it must have just been left over on my side when I switched branches or something.

Nice work :sparkles:

**Comment by malcommac** [comment]
np :+1: thank you!

**Comment by Hout** [comment]
Guys, do not we need to clean the directories and config settings?
If I look at the [keychain](https://github.com/kishikawakatsumi/KeychainAccess) example, I see:
- neatly divided file groups and directories for source code and tests
- a configuration file for each platform

screen shot 2016-01-31 at 12 09 13

**Comment by cjwirth** [comment]
I don't think there is a need for separate config setting files if you are satisfied with the way the settings are set up in the project file. It does centralize some of the settings, so it can be easier to change some settings for everything. 

You probably could move the `SwiftDate Tests` files into the `SwiftDateTests` group, and move the `SwiftDate Sources` files into the `SwiftDate` group. It might be a little cleaner, but I don't think it really makes much of a difference.

screen shot 2016-02-01 at 11 35 25 am

**Pull request closed without merging**
