### PR TITLE
Adopt a more straightforward approach with time differences

### PR DESCRIPTION
**Pull request by Hout**
Instead of convenience functions with "before" and "after", just calculates the difference in seconds, days etc. IMHO this is more straightforward.

### CODE REVIEW

**Comment by malcommac** [comment]
Great; yo made me come up with another idea: what about a single function ```timeDifference``` which can take an argument (ie. ```NSCalendarUnit``` or a custom one) and return the difference?
Something like  ```func timeDifference(unit: NSCalendarUnit, fromDate: NSDate)```

**Comment by Hout** [comment]
Good idea! We could create a small wrapper around components(fromDate, toDate) as specified in:
https://developer.apple.com/library/prerelease/ios/documentation/Cocoa/Conceptual/DatesAndTimes/Articles/dtCalendricalCalculations.html#//apple_ref/doc/uid/TP40007836-SW8

With that approach we can express the time difference in a set of time units. I will check it out the next days.

**Comment by Hout** [comment]
This would be a minimal but very functional wrapper:
````swift
    func difference(toDate: NSDate, unitFlags: NSCalendarUnit) -> NSDateComponents {
        let calendar = NSCalendar.currentCalendar()
        let components = calendar.components(unitFlags, fromDate: self, toDate: toDate, options: NSCalendarOptions(rawValue: 0))
        return components
    }
````

Where this would be a wrapper for just one unit:
````swift
    func difference(toDate: NSDate, unit: NSCalendarUnit) -> Int {
        let calendar = NSCalendar.currentCalendar()
        let components = calendar.components(unitFlags, fromDate: self, toDate: toDate, options: NSCalendarOptions(rawValue: 0))
        if unit.contains(.Year) {
            return components.Year
        } else
... etc
    }
````

What do you think?

**Comment by Hout** [comment]
Oops accidentally closed this one

**Comment by malcommac** [comment]
I think the first one is a more flexible approach. I'll add it to the base case right now, thank you :)

**Comment by malcommac** [comment]
Added it to 1.2 release. This is the commit 2ebb8d4fd8ec0bf3fda20efa46e136ec1bca2b51. What do you think?

**Comment by malcommac** [comment]
Tag 1.2 https://github.com/malcommac/SwiftDate/releases/tag/1.2

**Comment by Hout** [comment]
Woops! Hold horses pls. Ow too late. ;-)
Still working on your idea.

**Comment by malcommac** [comment]
:-) Great, thank you very much for this contribution, it's a great addition to have a more compact code.

**Pull request closed without merging**
