### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Hout**
Fixed many references to UTC-like behaviour.
Renamed Region to DateRegion
Split up into separate files
Consistent file naming
Consolidated many initialisation code into one.

TODO: mocking string tests
TODO: all comments in the headers
TODO: Documentation
TODO: Quick & Nimble
TODO: calendar and time zone extensions are not elegant enough

### CODE REVIEW

**Comment by malcommac** [comment]
We should create a develop branch to merge your changes and working to remaining TODO items. What do you think?
I was wrong releasing early 2.0 directly on master branch but I think we can make a develop branch and merge it in a 2.1 release when remaining changes will be completed. What do you think?

**Comment by malcommac** [comment]
You should be able (as collaborator) to create directly a develop branch, don't you?

**Comment by Hout** [comment]
Well, I already have but with you being the Godfather of `SwiftDate` I do not want to merge it into master without your blessing ;-)

**Comment by malcommac** [comment]
Ehehhe you have my blessing for these changes :) I think they are on the track to put the necessary consistency into the library to mark it "stable" and ready for production; so let's go, we will work on develop branch until 2.1 is ready to make it master.

**Comment by Hout** [comment]
All included in development branch, no pull necessary.

**Pull request closed without merging**
