### PR TITLE
Fix range at for swift 4

### PR DESCRIPTION
**Pull request by RamblinWreck77**
Swift 4 compatibility auto-fix in xcode

### CODE REVIEW

**Comment by malcommac** [comment]
I'm a bit perplexed. Your PR has the same content of the `DOTNETDateTimeFormatter` https://github.com/malcommac/SwiftDate/blob/feature/4.3.1/Sources/SwiftDate/DOTNETDateTimeFormatter.swift with `range(at)` replaced by `rangeAt()`

**Comment by RamblinWreck77** [comment]
I'm not sure why all of the other commits are visible, but unless I messed up somewhere Xcode 9 GM set to Swift 4 would not compile with 4.4.0, saying that range(at:) had been renamed to rangeAt() 

So I changed it and submitted a PR

**Comment by malcommac** [comment]
Can you made a new PR with the same changes? Directly to features/4.3.1 branch?
Thanks

**Comment by malcommac** [comment]
Let's try 4.4.1 and tell me if it's solved.

**Comment by madsb** [comment]
screen shot 2017-09-16 at 06 55 51
I still get this with 4.4.1

**Comment by malcommac** [comment]
In Swift 4.x project rangeAt() is renamed range(at:)
Are you sure you are using it in a Swift 4 project?

screen shot 2017-09-16 at 10 01 28

**Comment by malcommac** [comment]
Just a notice:

## Swift 3 and Swift 4 Compatibility

- **Swift 4.x**: >= 4.4.0 - Latest is 4.4.0 [Download here](https://github.com/malcommac/SwiftDate/releases/tag/4.4.0).
- **Swift 3.x**: Latest compatible version is 4.3.0 [Download here](https://github.com/malcommac/SwiftDate/releases/tag/4.3.0). If you are using CocoaPods be sure to fix the release (`pod 'SwiftDate', '~> 4.3.0'`)

**Comment by madsb** [comment]
Yeah, sorry - my mistake!

**Comment by malcommac** [comment]
No problem :)

**Pull request closed without merging**
